#%RAML 1.0 NamedExample
value:
  -
    companyName: "TransNational"
    origin:
        locationDesc: "My Location"
    destination:
        locationDesc: "Your Location"            
  - 
    companyName: "TransNational"
    origin:
        locationDesc: "My Location"
    destination:
        locationDesc: "Your Location"        