#%RAML 1.0 Trait
queryParameters:
          company_name:
            required: false
            type: string
          departure_loc:
            required: false
            type: string
          destination_loc:
            required: false
            type: string