#%RAML 1.0 NamedExample
value:
  - 
    companyName: "TravelOnTip"
    availableSeats: 20
    departureDateTime: "2023-02-09T10:55:00"
    travelRoute:
        destination: 
          locationDesc: "Your Location"
        origin:
          locationDesc: "My Location"     
  - 
    companyName: "TravelOnTip"
    availableSeats: 20
    departureDateTime: "2023-02-09T10:55:00"
    travelRoute: 
        destination: 
          locationDesc: "Your Location"
        origin:
            locationDesc: "My Location"       